#include "NativeHelloImpl.h"

#include <iostream>
#include <jni.h>
#include "com_glfrc_jni_JavaHello.h"   // auto-generated by `javah HelloWorld`


std::string NativeHello::DoSayHello(const std::string &name)
{
    return "Hello " + name;
}

JNIEXPORT jstring JNICALL Java_com_glfrc_jni_JavaHello_sayHello
  (JNIEnv *env, jobject thisObj, jstring arg)
{
    const char* name = env->GetStringUTFChars(arg, NULL);
    
    std::string hello = NativeHello::DoSayHello(name);

    env->ReleaseStringUTFChars(arg, name);  

    return env->NewStringUTF(hello.c_str());
}